config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:destroy]

  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  get '/user/:name', to: 'users#show'

  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get    '/r/:name',                 to: 'subreddits#show'
  get    '/subreddits/create',       to: 'subreddits#new'
  post   '/subreddits/create',       to: 'subreddits#create'
  get    '/subreddits/edit/:name',   to: 'subreddits#edit'
  post   '/subreddits/edit/:name',   to: 'subreddits#update'
  delete '/subreddits/delete/:name', to: 'subreddits#destroy'
  get    '/subreddits',              to: 'subreddits#index'
  get    '/r',                       to: 'subreddits#index'

  get    '/submit',                to: 'posts#new'
  post   '/submit',                to: 'posts#create'
  get    '/r/:subreddit_name/:id', to: 'posts#show'
  delete '/r/:subreddit_name/:id', to: 'posts#destroy'
  get    '/post/:id/edit',         to: 'posts#edit'
  post   '/post/:id/edit',         to: 'posts#update'

  post   '/r/:subreddit_name/:post_id/comment', to: 'comments#create'

  post   '/subscribe',   to: 'subscriptions#create'
  post   '/unsubscribe', to: 'subscriptions#destroy'

  get  '/post_title', to: 'meta_datas#get_title'
  post '/karma',      to: 'votes#update'
  post '/search',     to: 'search#new'

  # Static pages
  get '/legal', to: 'static_pages#legal'
  get '/about', to: 'static_pages#about'

  root 'front_pages#index'
end

app/views/shared/_comment.html.erb
<li class=comment>
  <div class=votes>
    <% if @comments_votes[comment.id].nil? %>
      <span id=uc<%= comment.id %> data=<%= comment.post.id %> class=upvote>&#8613;</span>
      <span id=dc<%= comment.id %> data=<%= comment.post.id %> class=downvote>&#8615;</span>
    <% elsif @comments_votes[comment.id] == 0 %>
      <span id=uc<%= comment.id %> data=<%= comment.post.id %> class=upvote>&#8613;</span>
      <span id=dc<%= comment.id %> data=<%= comment.post.id %> class='downvote downvoted'>&#8615;</span>
    <% else %>
      <span id=uc<%= comment.id %> data=<%= comment.post.id %> class='upvote upvoted'>&#8613;</span>
      <span id=dc<%= comment.id %> data=<%= comment.post.id %> class=downvote>&#8615;</span>
    <% end %>
  </div>
  <div class=comment_box>
    <span class=comment_header>
      <span class=bold><%= link_to comment.user.name, "/user/#{comment.user.name}" %></span>
       | <span id=kc<%= comment.id %> class=bold><%= comment.karma %></span> points
       | <%= time_ago_in_words(comment.created_at) %> agos
    </span>
    <span class=comment_content><%= comment.content %></span>
  </div>
</li>

app/views/shared/_post.html.erb
<% vote = @votes[post.id]     %>
<% if vote == 0               %>
<%   post_vote = " downvoted" %>
<% elsif vote == 1            %>
<%   post_vote = " upvoted"   %>
<% else                       %>
<%   post_vote = ""           %>
<% end                        %>

<% default_thumbnail = post.post_type == 0 ? "http://i.imgur.com/vKvm5pe.jpg" : "http://i.imgur.com/B9phcsk.jpg" %>

<div class=post>
  <div class=votes>
    <span id=up<%= post.id %> data="-1" class='upvote<%= post_vote unless post_vote == " downvoted" %>'>&#8613;</span>
    <span id=kp<%= post.id %> data="-1" class='karma<%= post_vote %>'><%= post.karma %></span>
    <span id=dp<%= post.id %> data="-1" class='downvote<%= post_vote unless post_vote == " upvoted" %>'>&#8615;</span>
  </div>
  <div class=thumbnail_box>
    <%= link_to post.link do %>
      <%= image_tag post.thumbnail || default_thumbnail, class: 'post_thumbnail' %>
    <% end %>
  </div>
  <div class=post_details>
    <div class=post_title>
      <%= link_to post.title, post.link, class: "title_text" %>
      <% if post.post_type == 0 %>
        <% if @subreddit.nil? %>
          <span class=title_host>(self.<%= post.subreddit.name %>)</span>
        <% else %>
          <span class=title_host>(self.<%= @subreddit.name %>)</span>
        <% end %>
      <% else %>
        <span class=title_host> - (<%= URI.parse(post.link).host rescue "" %>)</span>
      <% end %>
    </div>
    <div class=post_meta>
      <span>Submitted <%= time_ago_in_words(post.created_at) %> ago by </span>
      <%= link_to post.user.name, "/user/#{post.user.name}" %>
      <% if controller_name == "front_pages" %>
        to <%= link_to "r/#{post.subreddit.name}", "/r/#{post.subreddit.name}" %>
      <% end %>
    </div>
    <% if @subreddit.nil? %>
      <%= link_to pluralize(post.comment_count, "comment"), "/r/#{post.subreddit.name}/#{post.id}" %>
    <% else %>
      <%= link_to pluralize(post.comment_count, "comment"), "/r/#{@subreddit.name}/#{post.id}" %>
    <% end %>
    <% if controller_name == "posts" && @post.post_type == 0 && !@post.post_text.blank? %>
      <div class=post_text_box><%= @post.post_text %></div>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<% random_image = ["http://i.imgur.com/QcC2Mf4.jpg", "http://i.imgur.com/5vGHZTZ.jpg", %>
<%                 "http://i.imgur.com/QjNSFPu.png", "http://i.imgur.com/ZbDR3Xq.jpg", %>
<%                 "http://i.imgur.com/T2Hld7B.png"]                                   %>

<div class=sidebar>
  <div class=search_box>
    <%= form_for(:search, url: search_path) do |f| %>
      <%= f.text_field :search, class: "search_text", placeholder: "search" %>
      <%= f.submit "\u26B2", class: "search_btn" %>
    <% end %>
  </div>
  <% if logged_in? %>
    <%= link_to "Submit a new post", submit_path, class: "big_link" %>
    <%= link_to "Create your own subreddit", subreddits_create_path, class: "big_link" %>
  <% else %>
    <div class=login_box>
      <%= form_for(:session, url: login_path) do |f| %>
        <div class=login1>
          <%= f.text_field :name, placeholder: "username" %>

          <%= f.password_field :password, placeholder: "password" %>
        </div>
        <div class=login2>
          <%= f.label :remember_me, class: "remember_me" do %>
            <%= f.check_box :remember_me %>
            <span>Remember me</span>
          <% end %>

          <%= f.submit "login", class: "btn-primary" %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= link_to "https://www.reddit.com", rel:"noopener noreferrer", target:"_blank" do %>
    <%= image_tag random_image.sample %>
  <% end %>
  <div class="sidebar_text">
    <%= yield(:sidebar_text) %>
    <% if (["subreddits", "posts"].include? controller_name) && !yield(:moderator).blank? %>
      <div class=mod_info>
        Moderator: <%= link_to yield(:moderator), "/user/#{yield(:moderator)}" %>
      </div>
    <% end %>
  </div>
</div>