config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:destroy]

  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  get '/user/:name', to: 'users#show'

  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get    '/r/:name',                 to: 'subreddits#show'
  get    '/subreddits/create',       to: 'subreddits#new'
  post   '/subreddits/create',       to: 'subreddits#create'
  get    '/subreddits/edit/:name',   to: 'subreddits#edit'
  post   '/subreddits/edit/:name',   to: 'subreddits#update'
  delete '/subreddits/delete/:name', to: 'subreddits#destroy'
  get    '/subreddits',              to: 'subreddits#index'
  get    '/r',                       to: 'subreddits#index'

  get    '/submit',                to: 'posts#new'
  post   '/submit',                to: 'posts#create'
  get    '/r/:subreddit_name/:id', to: 'posts#show'
  delete '/r/:subreddit_name/:id', to: 'posts#destroy'
  get    '/post/:id/edit',         to: 'posts#edit'
  post   '/post/:id/edit',         to: 'posts#update'

  post   '/r/:subreddit_name/:post_id/comment', to: 'comments#create'

  post   '/subscribe',   to: 'subscriptions#create'
  post   '/unsubscribe', to: 'subscriptions#destroy'

  get  '/post_title', to: 'meta_datas#get_title'
  post '/karma',      to: 'votes#update'
  post '/search',     to: 'search#new'

  # Static pages
  get '/legal', to: 'static_pages#legal'
  get '/about', to: 'static_pages#about'

  root 'front_pages#index'
end

app/models/subreddit.rb
class Subreddit < ApplicationRecord
  has_many :subscriptions, dependent: :destroy
  has_many :posts,         dependent: :destroy
  has_many :users,         through: :subscriptions

  attr_accessor :moderator

  BAD_NAME_REGEX  = /[^\w-]+/

  before_save { name.downcase! }

  validates :name, presence: true,
                   length: { in: 3..21 },
                   format: { without: BAD_NAME_REGEX },
                   uniqueness: { case_sensitive: false }

  validates :description, length: { maximum: 500 }
  validates :sidebar,     length: { maximum: 500 }
  validates :nsfw,        inclusion: { in: [ true, false ] }
  validates :mod,         presence: true

  def moderator
    @moderator ||= User.find(mod)
  end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController

  def index
    @subreddits = Subreddit.order("subscriptions_count DESC").all.
                            paginate(page: params[:page], per_page: 30)
    @subscriptions = Subscription.where(user_id: current_user.id).
                                  pluck(:subreddit_id) rescue nil
  end

  def new
    @subreddit = Subreddit.new
  end

  def create
    @subreddit = Subreddit.new(sub_params)
    @subreddit.mod = current_user.id if logged_in?

    if @subreddit.save
      flash[:information] = "Subreddit successfully created!"
      current_user.subreddits << @subreddit

      redirect_to "/r/#{@subreddit.name}"
    else
      render :new
    end
  end

  def show
    @subreddit = Subreddit.find_by(name: params[:name])
    if @subreddit.nil?
      flash.now[:information] = "r/#{params[:name]} doesn't exist.\nWhy don't you create it?"
      @posts = []
    else
      @posts = @subreddit.posts.where("upvotes - downvotes > -10").
                                paginate(page: params[:page], per_page: 30)

      @votes = Hash.new
      if logged_in?
        user_votes = Vote.where(user_id: current_user.id, comment_id: nil)

        user_votes.each do |vote|
          @votes[vote.post_id] = vote.vote
        end
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def sub_params
      params.require(:subreddit).permit(:name,
                                        :description,
                                        :sidebar,
                                        :nsfw)
    end
end

app/views/subreddits/_form.html.erb
<%= form_for(@subreddit, url: yield(:form_path)) do |f| %>
  <% if @subreddit.errors.any? %>
    <div id=error_explanation>
      <div class=alert>
        The form contains <%= pluralize(@subreddit.errors.full_messages.uniq.count, "error") %>.
      </div>
      <ul>
        <% @subreddit.errors.full_messages.uniq.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% unless @subreddit.created_at? %>
    <%= f.label :name %>
    <span>Only letters, numbers, and underscores, permitted.<br/>The name cannot be changed once created.</span>
    <%= f.text_field :name %>
  <% end %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :sidebar %>
  <span>This appears on the sidebar of your subreddits page.</span>
  <%= f.text_area :sidebar %>

  <%= f.label :nsfw, class: "checkbox" do %>
    <%= f.check_box :nsfw %>
    <span>NSFW (Mature content)</span>
  <% end %>

  <%= f.submit yield(:button) %>

<% end %>

app/views/subreddits/edit.html.erb
<% provide(:title, "Edit Subreddit") %>
<% provide(:button, "Update") %>
<% provide(:form_path, subreddits_edit_path) %>
<div class=main>
  <div class=box>
    <h3>Create a Subreddit</h3>
    <%= render "form" %>
  </div>
</div>

app/views/subreddits/index.html.erb
<% provide(:title, "Subreddits") %>
<div class=main>
  <div class=box>
    <h3>Subreddits</h3>
    <% @subreddits.each do |sub| %>
      <div class=sub>
        <% if @subscriptions && (@subscriptions.include? sub.id) %>
          <span class='unsubscribe button' data=<%= sub.id %>>unsubscribe</span>
        <% elsif logged_in? %>
          <span class='subscribe button' data=<%= sub.id %>>subscribe</span>
        <% end %>
        <div class=sub_details>
          <%= link_to "r/#{sub.name}", "/r/#{sub.name}" %>
          <% if sub.nsfw %>
            <span class=nsfw>NSFW</span>
          <% end %>
          <span class=sub_description><%= sub.description %></span>
          <div class=sub_meta>
            <span class=bold><%= number_with_delimiter(sub.subscriptions_count) %> subscribers</span>
            , a community for <%= time_ago_in_words(sub.created_at) %>
          </div>
        </div>
      </div>
    <% end %>

    <%= will_paginate @subreddits %>
  </div>
  <%= render "shared/sidebar" %>
</div>

app/views/subreddits/new.html.erb
<% provide(:title, "Create Subreddit") %>
<% provide(:button, "Create") %>
<% provide(:form_path, subreddits_create_path) %>
<div class=main>
  <div class=box>
    <h3>Create a Subreddit</h3>
    <%= render "form" %>
  </div>
</div>

app/views/subreddits/show.html.erb
<% provide(:title, @subreddit.nil? ? "Error" : @subreddit.name) %>
<div class=main>
  <div class=box>
    <% unless @subreddit.nil? %>
      <% provide(:sidebar_text, @subreddit.sidebar)     %>
      <% provide(:moderator, @subreddit.moderator.name) %>

      <h3>r/<%= @subreddit.name %></h3>

      <% @posts.each do |post| %>
        <%= render partial: "shared/post", locals: {post: post} %>
      <% end %>

      <%= will_paginate @posts %>
    <% end %>
  </div>
  <%= render "shared/sidebar" %>
</div>