config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:destroy]

  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  get '/user/:name', to: 'users#show'

  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get    '/r/:name',                 to: 'subreddits#show'
  get    '/subreddits/create',       to: 'subreddits#new'
  post   '/subreddits/create',       to: 'subreddits#create'
  get    '/subreddits/edit/:name',   to: 'subreddits#edit'
  post   '/subreddits/edit/:name',   to: 'subreddits#update'
  delete '/subreddits/delete/:name', to: 'subreddits#destroy'
  get    '/subreddits',              to: 'subreddits#index'
  get    '/r',                       to: 'subreddits#index'

  get    '/submit',                to: 'posts#new'
  post   '/submit',                to: 'posts#create'
  get    '/r/:subreddit_name/:id', to: 'posts#show'
  delete '/r/:subreddit_name/:id', to: 'posts#destroy'
  get    '/post/:id/edit',         to: 'posts#edit'
  post   '/post/:id/edit',         to: 'posts#update'

  post   '/r/:subreddit_name/:post_id/comment', to: 'comments#create'

  post   '/subscribe',   to: 'subscriptions#create'
  post   '/unsubscribe', to: 'subscriptions#destroy'

  get  '/post_title', to: 'meta_datas#get_title'
  post '/karma',      to: 'votes#update'
  post '/search',     to: 'search#new'

  # Static pages
  get '/legal', to: 'static_pages#legal'
  get '/about', to: 'static_pages#about'

  root 'front_pages#index'
end

app/views/layouts/_flasher.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<div class=footer>
  <span>
    Micro-Reddit was built by <a rel="noopener noreferrer"
                                 target="_blank"
                                 href="http://www.thomasrudge.co.uk">Thomas Rudge</a>.
    <br/>
    Codebase can be found <a rel="noopener noreferrer"
                             target="_blank"
                             href="https://github.com/Thomas-Rudge/micro_reddit">here</a>.
  </span>
  <nav>
    <ul>
      <li><%= link_to "About", about_path, class: "footer_link" %></li>
       |
      <li><a rel="noopener noreferrer"
             target="_blank"
             class=footer_link
             href="http://www.thomasrudge.co.uk/html/contact.html">Contact</a></li>
       |
      <li><%= link_to "Legal", legal_path, class: "footer_link" %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_header.html.erb
<div class=header>
  <div class=topbar>
    <div id=sub_list>
      <span id=my_subreddits>my subreddits</span>
      <ul id=topbar_wrapper>
        <% current_popular_subreddits.each do |subreddit| %>
           <li class=topbar_subreddits><%= link_to " - #{subreddit}", "/r/#{subreddit}" %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div id=my_subreddit_list>
    <% if logged_in? %>
      <ul>
        <% current_users_subreddits.each do |subreddit| %>
          <li><%= link_to subreddit, "/r/#{subreddit}" %></li>
        <% end %>
      </ul>
    <% else %>
      <%= link_to "login or signup ", signup_path, class: 'prompt' %>
    <% end %>
  </div>
  <%= link_to "more...", "/subreddits", id: "more_subreddits" %>
  <div>
    <h1><span>micro</span><%= link_to "reddit", root_path %></h1>
    <div class=access>
      <span>
        <% if logged_in? %>
          <%= link_to current_user.name, "/user/#{current_user.name}" %>

          (<span class=bold><%= current_user.post_karma %> - <%= current_user.comment_karma %></span>)
           |
          <%= link_to "logout", logout_path %>
        <% else %>
          <%= "Want to join?" %>
          <%= link_to "login or signup ", signup_path %>
          <%= "in seconds!" %>
        <% end %>
      </span>
    </div>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src='https://www.google.com/recaptcha/api.js'></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class=sidebar>
  <div class=search_box>
    <%= form_for(:search, url: "#") do |f| %>
      <%= f.text_field :search, class: "search_text", placeholder: "search" %>
      <%= f.submit "\u26B2", class: "search_btn" %>
    <% end %>
  </div>
  <% if logged_in? %>
    <%= link_to "Submit a new post", "#", class: "big_link" %>
    <%= link_to "Create your own subreddit", subreddits_create_path, class: "big_link" %>
  <% else %>
    <div class=login_box>
      <%= form_for(:session, url: login_path) do |f| %>
        <div class=login1>
          <%= f.text_field :name, placeholder: "username" %>

          <%= f.password_field :password, placeholder: "password" %>
        </div>
        <div class=login2>
          <%= f.label :remember_me, class: "remember_me" do %>
            <%= f.check_box :remember_me %>
            <span>Remember me</span>
          <% end %>

          <%= f.submit "login", class: "btn-primary" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <div class="wrapper">
      <%= render "layouts/header" %>
      <div class="wrapper main-content">
        <%= render "layouts/flasher" %>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
  <%= debug(params) if Rails.env.development? && false %>
</html>